[tes]
repo = "https://github.com/DanteDev2102/uwe.git"
short = ""
long = ""

[tesu]
repo = ""
short = ""
long = ""

[tesi]
repo = ""
short = ""
long = ""

[te]
repo = ""
short = ""
long = ""

[jejeje]
repo = ""
branch = "jelo"
tag = "uiui"
summary = "kekekeke"
description = "jelo"

[jeje]
repo = ""
branch = "jelo"
tag = "uiui"
summary = "kekekeke"
description = "jelo"

[jej]
repo = ""
